<!DOCTYPE GUIXML>
<VisualCommand Title="" AppName="" WebSite="" Description="" Mac="False" Windows="False" Linux="False" >
 <Container Type="Tab" Name="Basic Startup" >
  <checkBoxEditor StringFormat="--version " Description="Display the version of Wget. " Required="True" RequiredChecked="False" />
  <checkBoxEditor StringFormat="--help " Description="Print a help message describing all of Wget's command-line options. " Required="True" RequiredChecked="False" />
  <checkBoxEditor StringFormat="--background" Description="Go to background immediately after startup. If no output file is specified via the ‘-o’, output is redirected to wget-log. " Required="True" RequiredChecked="False" />
  <StringEditor String="" StringFormat="--execute %s" Description="Execute command as if it were a part of .wgetrc (see Startup File). A command thus invoked will be executed after the commands in .wgetrc, thus taking precedence over them. If you need to specify more than one wgetrc command, use multiple instances of ‘-e’. " Required="True" RequiredChecked="False" />
 </Container>
 <Container Type="Tab" Name="Logging and input file:" >
  <FileForm Mode="4" Filter="All Files(*.*)" StringFormat="--output-file=%s" Description="log messages to FILE." Required="True" Seperator=";" RequiredChecked="False" Surround="&quot;%s&quot;" />
  <FileForm Mode="4" Filter="All Files(*.*)" StringFormat="--append-output=%s" Description="append messages to FILE." Required="True" Seperator=";" RequiredChecked="False" Surround="&quot;%s&quot;" />
  <checkBoxEditor StringFormat="--debug " Description="print lots of debugging information." Required="True" RequiredChecked="False" />
  <checkBoxEditor StringFormat="--quiet " Description="Turn off Wget's output" Required="True" RequiredChecked="False" />
  <checkBoxEditor StringFormat="--verbose " Description="Turn on verbose output, with all the available data. The default output is verbose. " Required="True" RequiredChecked="False" />
  <checkBoxEditor StringFormat="--no-verbose " Description="Turn off verbose without being completely quiet (use ‘-q’ for that), which means that error messages and basic information still get printed. " Required="True" RequiredChecked="False" />
  <FileForm Mode="0" Filter="All Files(*.*)" StringFormat="--input-file=%s" Description="Read urls from file. If ‘-’ is specified as file, urls are read from the standard input. (Use ‘./-’ to read from a file literally named ‘-’.) &#xa;If this function is used, no urls need be present on the command line. If there are urls both on the command line and in an input file, those on the command lines will be the first ones to be retrieved. The file need not be an html document (but no harm if it is)—it is enough if the urls are just listed sequentially. &#xa;However, if you specify ‘--force-html’, the document will be regarded as ‘html’. In that case you may have problems with relative links, which you can solve either by adding &lt;base href=&quot;url&quot;> to the documents or by specifying ‘--base=url’ on the command line. " Required="True" Seperator=";" RequiredChecked="False" Surround="&quot;%s&quot;" />
  <checkBoxEditor StringFormat="--force-html " Description="When input is read from a file, force it to be treated as an html file. This enables you to retrieve relative links from existing html files on your local disk, by adding &lt;base href=&quot;url&quot;> to html, or using the ‘--base’ command-line option. " Required="True" RequiredChecked="False" />
  <StringEditor String="" StringFormat="--base=%s" Description="Prepends URL to relative links read from the file specified with the ‘-i’ option. " Required="True" RequiredChecked="False" />
 </Container>
 <Container Type="Tab" Name="Download Options" >
  <StringEditor String="" StringFormat="--bind-address=%s" Description="When making client TCP/IP connections, bind to ADDRESS on the local machine. ADDRESS may be specified as a hostname or IP address. This option can be useful if your machine is bound to multiple IPs. " Required="True" RequiredChecked="False" />
  <NumericalForm StringFormat="--tries=%s" Number="0" Description="Set number of retries to number. Specify 0 or ‘inf’ for infinite retrying. The default is to retry 20 times, with the exception of fatal errors like “connection refused” or “not found” (404), which are not retried. " Required="True" RequiredChecked="False" Min="0" Max="2147483647" />
  <FileForm Mode="0" Filter="All Files(*.*)" StringFormat="--output-document=%s" Description="The documents will not be written to the appropriate files, but all will be concatenated together and written to file. If ‘-’ is used as file, documents will be printed to standard output, disabling link conversion. (Use ‘./-’ to print to a file literally named ‘-’.) &#xa;Use of ‘-O’ is not intended to mean simply “use the name file instead of the one in the URL;” rather, it is analogous to shell redirection: ‘wget -O file http://foo’ is intended to work like ‘wget -O - http://foo > file’; file will be truncated immediately, and all downloaded content will be written there. &#xa;For this reason, ‘-N’ (for timestamp-checking) is not supported in combination with ‘-O’: since file is always newly created, it will always have a very new timestamp. A warning will be issued if this combination is used. &#xa;Similarly, using ‘-r’ or ‘-p’ with ‘-O’ may not work as you expect: Wget won't just download the first file to file and then download the rest to their normal names: all downloaded content will be placed in file. This was disabled in version 1.11, but has been reinstated (with a warning) in 1.11.2, as there are some cases where this behavior can actually have some use. &#xa;Note that a combination with ‘-k’ is only permitted when downloading a single document, as in that case it will just convert all relative URIs to external ones; ‘-k’ makes no sense for multiple URIs when they're all being downloaded to a single file. " Required="True" Seperator=";" RequiredChecked="False" Surround="&quot;%s&quot;" />
  <checkBoxEditor StringFormat="--no-clobber" Description="If a file is downloaded more than once in the same directory, Wget's behavior depends on a few options, including ‘-nc’. In certain cases, the local file will be clobbered, or overwritten, upon repeated download. In other cases it will be preserved. &#xa;When running Wget without ‘-N’, ‘-nc’, ‘-r’, or ‘p’, downloading the same file in the same directory will result in the original copy of file being preserved and the second copy being named ‘file.1’. If that file is downloaded yet again, the third copy will be named ‘file.2’, and so on. When ‘-nc’ is specified, this behavior is suppressed, and Wget will refuse to download newer copies of ‘file’. Therefore, “no-clobber” is actually a misnomer in this mode—it's not clobbering that's prevented (as the numeric suffixes were already preventing clobbering), but rather the multiple version saving that's prevented. &#xa;When running Wget with ‘-r’ or ‘-p’, but without ‘-N’ or ‘-nc’, re-downloading a file will result in the new copy simply overwriting the old. Adding ‘-nc’ will prevent this behavior, instead causing the original version to be preserved and any newer copies on the server to be ignored. &#xa;When running Wget with ‘-N’, with or without ‘-r’ or ‘-p’, the decision as to whether or not to download a newer copy of a file depends on the local and remote timestamp and size of the file (see Time-Stamping). ‘-nc’ may not be specified at the same time as ‘-N’. &#xa;Note that when ‘-nc’ is specified, files with the suffixes ‘.html’ or ‘.htm’ will be loaded from the local disk and parsed as if they had been retrieved from the Web. " Required="True" RequiredChecked="False" />
  <checkBoxEditor StringFormat="--continue " Description="Continue getting a partially-downloaded file. This is useful when you want to finish up a download started by a previous instance of Wget, or by another program. For instance: &#xa;          wget -c ftp://sunsite.doc.ic.ac.uk/ls-lR.Z &#xa;If there is a file named ls-lR.Z in the current directory, Wget will assume that it is the first portion of the remote file, and will ask the server to continue the retrieval from an offset equal to the length of the local file. &#xa;Note that you don't need to specify this option if you just want the current invocation of Wget to retry downloading a file should the connection be lost midway through. This is the default behavior. ‘-c’ only affects resumption of downloads started prior to this invocation of Wget, and whose local files are still sitting around. &#xa;Without ‘-c’, the previous example would just download the remote file to ls-lR.Z.1, leaving the truncated ls-lR.Z file alone. &#xa;Beginning with Wget 1.7, if you use ‘-c’ on a non-empty file, and it turns out that the server does not support continued downloading, Wget will refuse to start the download from scratch, which would effectively ruin existing contents. If you really want the download to start from scratch, remove the file. &#xa;Also beginning with Wget 1.7, if you use ‘-c’ on a file which is of equal size as the one on the server, Wget will refuse to download the file and print an explanatory message. The same happens when the file is smaller on the server than locally (presumably because it was changed on the server since your last download attempt)—because “continuing” is not meaningful, no download occurs. &#xa;On the other side of the coin, while using ‘-c’, any file that's bigger on the server than locally will be considered an incomplete download and only (length(remote) - length(local)) bytes will be downloaded and tacked onto the end of the local file. This behavior can be desirable in certain cases—for instance, you can use ‘wget -c’ to download just the new portion that's been appended to a data collection or log file. &#xa;However, if the file is bigger on the server because it's been changed, as opposed to just appended to, you'll end up with a garbled file. Wget has no way of verifying that the local file is really a valid prefix of the remote file. You need to be especially careful of this when using ‘-c’ in conjunction with ‘-r’, since every file will be considered as an &quot;incomplete download&quot; candidate. &#xa;Another instance where you'll get a garbled file if you try to use ‘-c’ is if you have a lame http proxy that inserts a “transfer interrupted” string into the local file. In the future a “rollback” option may be added to deal with this case. &#xa;Note that ‘-c’ only works with ftp servers and with http servers that support the Range header. &#xa;" Required="True" RequiredChecked="False" />
  <StringEditor String="" StringFormat="--progress=%s" Description="Select the type of the progress indicator you wish to use. Legal indicators are “dot” and “bar”. &#xa;The “bar” indicator is used by default. It draws an ascii progress bar graphics (a.k.a “thermometer” display) indicating the status of retrieval. If the output is not a TTY, the “dot” bar will be used by default. &#xa;Use ‘--progress=dot’ to switch to the “dot” display. It traces the retrieval by printing dots on the screen, each dot representing a fixed amount of downloaded data. &#xa;When using the dotted retrieval, you may also set the style by specifying the type as ‘dot:style’. Different styles assign different meaning to one dot. With the default style each dot represents 1K, there are ten dots in a cluster and 50 dots in a line. The binary style has a more “computer”-like orientation—8K dots, 16-dots clusters and 48 dots per line (which makes for 384K lines). The mega style is suitable for downloading very large files—each dot represents 64K retrieved, there are eight dots in a cluster, and 48 dots on each line (so each line contains 3M). &#xa;Note that you can set the default style using the progress command in .wgetrc. That setting may be overridden from the command line. The exception is that, when the output is not a TTY, the “dot” progress will be favored over “bar”. To force the bar output, use ‘--progress=bar:force’. " Required="True" RequiredChecked="False" />
  <checkBoxEditor StringFormat="--timestamping " Description="Turn on time-stamping. See Time-Stamping, for details. " Required="True" RequiredChecked="False" />
  <checkBoxEditor StringFormat="--server-response " Description="Print the headers sent by http servers and responses sent by ftp servers. " Required="True" RequiredChecked="False" />
  <checkBoxEditor StringFormat="--spider " Description="When invoked with this option, Wget will behave as a Web spider, which means that it will not download the pages, just check that they are there. For example, you can use Wget to check your bookmarks: &#xa;          wget --spider --force-html -i bookmarks.html &#xa;This feature needs much more work for Wget to get close to the functionality of real web spiders. " Required="True" RequiredChecked="False" />
  <NumericalForm StringFormat="--timeout=%s" Number="174408824" Description="Set the network timeout to seconds seconds. This is equivalent to specifying ‘--dns-timeout’, ‘--connect-timeout’, and ‘--read-timeout’, all at the same time. &#xa;When interacting with the network, Wget can check for timeout and abort the operation if it takes too long. This prevents anomalies like hanging reads and infinite connects. The only timeout enabled by default is a 900-second read timeout. Setting a timeout to 0 disables it altogether. Unless you know what you are doing, it is best not to change the default timeout settings. &#xa;All timeout-related options accept decimal values, as well as subsecond values. For example, ‘0.1’ seconds is a legal (though unwise) choice of timeout. Subsecond timeouts are useful for checking server response times or for testing network latency. " Required="True" RequiredChecked="False" Min="0" Max="2147483647" />
  <NumericalForm StringFormat="--dns-timeout=%s" Number="174425456" Description="Set the DNS lookup timeout to seconds seconds. DNS lookups that don't complete within the specified time will fail. By default, there is no timeout on DNS lookups, other than that implemented by system libraries. " Required="True" RequiredChecked="False" Min="0" Max="2147483647" />
  <NumericalForm StringFormat="--connect-timeout=%s" Number="174465336" Description="Set the connect timeout to seconds seconds. TCP connections that take longer to establish will be aborted. By default, there is no connect timeout, other than that implemented by system libraries. " Required="True" RequiredChecked="False" Min="0" Max="2147483647" />
  <NumericalForm StringFormat="--read-timeout=%s" Number="174504248" Description="Set the read (and write) timeout to seconds seconds. The “time” of this timeout refers to idle time: if, at any point in the download, no data is received for more than the specified number of seconds, reading fails and the download is restarted. This option does not directly affect the duration of the entire download. &#xa;Of course, the remote server may choose to terminate the connection sooner than this option requires. The default read timeout is 900 seconds. " Required="True" RequiredChecked="False" Min="0" Max="2147483647" />
  <StringEditor String="" StringFormat="--limit-rate=%s" Description="Limit the download speed to amount bytes per second. Amount may be expressed in bytes, kilobytes with the ‘k’ suffix, or megabytes with the ‘m’ suffix. For example, ‘--limit-rate=20k’ will limit the retrieval rate to 20KB/s. This is useful when, for whatever reason, you don't want Wget to consume the entire available bandwidth. &#xa;This option allows the use of decimal numbers, usually in conjunction with power suffixes; for example, ‘--limit-rate=2.5k’ is a legal value. &#xa;Note that Wget implements the limiting by sleeping the appropriate amount of time after a network read that took less time than specified by the rate. Eventually this strategy causes the TCP transfer to slow down to approximately the specified rate. However, it may take some time for this balance to be achieved, so don't be surprised if limiting the rate doesn't work well with very small files. " Required="True" RequiredChecked="False" />
 </Container>
</VisualCommand>
